Repository space-station-lore/corvax-lore, pull requests merged in 2025-05, with the labels that each got.

#71 Расширение диздока Синдиката
  05_Организации/Синдикат/design_document.md
Labels: Организации, Изменение

#70 Состояние мира Space Station 14
  01_Вселенная/Хронология/Наше_время/design_document.md
Labels: Вселенная, Изменение

#64 Диздок Редспейса
  10_Явления/Редспейс/design_document.md
Labels: Явления, Новый контент, Изменение

#59 Диздок Waffle Co
  04_Корпорации/Waffle_Co./design_document.md
Labels: Корпорации, Новый контент, Изменение
